In [2]:
import databento as db
import os
import pandas as pd
import numpy as np

In [11]:
client = db.Historical(key=os.getenv("DATABENTO_API_KEY"))

In [14]:
params = {
    "dataset": "GLBX.MDP3",
    "symbols": "GC.c.0, GC.c.1, GC.c.2, GC.c.6, GC.c.12",
    "stype_in": "continuous",
    "schema": "ohlcv-1d",
    "start": "2010-06-06",
    "end": "2025-08-18"
}

cost = client.metadata.get_cost(**params)
print(f"Estimated cost for this download: ${cost:.2f}")

Estimated cost for this download: $0.18

In [ ]:
# don't run again
# data = client.timeseries.get_range(**params)

C:\Users\semic\AppData\Local\Temp\ipykernel_4264\834081826.py:1: BentoWarning: The streaming request contained one or more days which have reduced quality: 2017-11-13 (degraded), 2018-10-21 (degraded), 2019-01-15 (degraded)... See: https://databento.com/docs/api-reference-historical/metadata/metadata-get-dataset-condition
  data = client.timeseries.get_range(**params)

In [58]:
df = pd.read_csv(r"Data\gold_continuous_futures.csv")

In [36]:
mini_df = df[df['symbol'] == 'GC.c.0'].copy()
last_day = mini_df['instrument_id'] != mini_df['instrument_id'].shift(-1)
print(f"Average volume on contract rollover days: {mini_df.loc[last_day, 'volume'].mean():.2f}")

Average volume on contract rollover days: 44.40

In [38]:
roll_adj = mini_df.loc[last_day, 'open'].shift(-1) - mini_df.loc[last_day, 'close']
print(f"Average roll adjustment on contract rollover days: {roll_adj.mean():.2f}")

Average roll adjustment on contract rollover days: 12.12

In [39]:
gen_adj = mini_df['open'].shift(-1) - mini_df['close']
print(f"Average daily adjustment: {gen_adj.mean()}")

Average daily adjustment: 0.28861374119931965

In [34]:
df.index[last_day]

DatetimeIndex(['2010-06-07 00:00:00+00:00', '2010-06-07 00:00:00+00:00',
               '2010-06-07 00:00:00+00:00', '2010-06-07 00:00:00+00:00',
               '2010-06-08 00:00:00+00:00', '2010-06-08 00:00:00+00:00',
               '2010-06-08 00:00:00+00:00', '2010-06-08 00:00:00+00:00',
               '2010-06-08 00:00:00+00:00', '2010-06-09 00:00:00+00:00',
               ...
               '2025-08-15 00:00:00+00:00', '2025-08-15 00:00:00+00:00',
               '2025-08-15 00:00:00+00:00', '2025-08-15 00:00:00+00:00',
               '2025-08-15 00:00:00+00:00', '2025-08-17 00:00:00+00:00',
               '2025-08-17 00:00:00+00:00', '2025-08-17 00:00:00+00:00',
               '2025-08-17 00:00:00+00:00', '2025-08-17 00:00:00+00:00'],
              dtype='datetime64[ns, UTC]', name='ts_event', length=18085, freq=None)

In [25]:
df[df['symbol'] == 'GC.c.0'].head(30)

,rtype,publisher_id,instrument_id,open,high,low,close,volume,symbol
ts_event,,,,,,,,,
2010-06-07 00:00:00+00:00,35,1,197009,1215.1,1244.7,1211.0,1241.6,860,GC.c.0
2010-06-08 00:00:00+00:00,35,1,197009,1238.7,1252.1,1234.1,1237.0,761,GC.c.0
2010-06-09 00:00:00+00:00,35,1,197009,1238.2,1238.2,1222.0,1231.6,419,GC.c.0
2010-06-10 00:00:00+00:00,35,1,197009,1230.8,1230.8,1215.1,1217.1,478,GC.c.0
2010-06-11 00:00:00+00:00,35,1,197009,1219.5,1229.6,1218.0,1227.0,179,GC.c.0
2010-06-13 00:00:00+00:00,35,1,197009,1230.2,1230.2,1230.2,1230.2,1,GC.c.0
2010-06-14 00:00:00+00:00,35,1,197009,1232.0,1232.7,1217.7,1222.3,229,GC.c.0
2010-06-15 00:00:00+00:00,35,1,197009,1224.0,1236.0,1222.4,1233.5,242,GC.c.0
2010-06-16 00:00:00+00:00,35,1,197009,1232.0,1237.6,1228.5,1230.4,297,GC.c.0
2010-06-17 00:00:00+00:00,35,1,197009,1233.9,1251.1,1233.9,1247.2,266,GC.c.0
2010-06-18 00:00:00+00:00,35,1,197009,1247.7,1261.5,1242.9,1256.1,130,GC.c.0
2010-06-21 00:00:00+00:00,35,1,197009,1257.4,1264.8,1232.0,1232.2,219,GC.c.0
2010-06-22 00:00:00+00:00,35,1,197009,1239.5,1242.8,1232.1,1241.0,172,GC.c.0
2010-06-23 00:00:00+00:00,35,1,197009,1240.2,1245.1,1226.9,1237.3,100,GC.c.0
2010-06-24 00:00:00+00:00,35,1,197009,1236.4,1248.4,1230.7,1243.6,161,GC.c.0
2010-06-25 00:00:00+00:00,35,1,197009,1243.3,1257.0,1243.3,1256.0,152,GC.c.0
2010-06-28 00:00:00+00:00,35,1,197009,1256.1,1262.2,1238.0,1239.2,46,GC.c.0
2010-06-29 00:00:00+00:00,35,1,102338,1241.2,1245.0,1228.5,1241.8,416,GC.c.0
2010-06-30 00:00:00+00:00,35,1,102338,1243.5,1246.2,1236.7,1241.8,73,GC.c.0
2010-07-01 00:00:00+00:00,35,1,102338,1241.7,1242.4,1201.4,1202.1,52,GC.c.0
2010-07-02 00:00:00+00:00,35,1,102338,1205.8,1211.6,1200.8,1210.0,167,GC.c.0
2010-07-05 00:00:00+00:00,35,1,102338,1210.7,1210.7,1206.2,1206.7,9,GC.c.0
2010-07-06 00:00:00+00:00,35,1,102338,1207.7,1211.8,1190.0,1193.0,43,GC.c.0
2010-07-07 00:00:00+00:00,35,1,102338,1185.8,1198.7,1185.3,1198.7,18,GC.c.0
2010-07-08 00:00:00+00:00,35,1,102338,1203.3,1203.3,1189.3,1198.5,97,GC.c.0
2010-07-09 00:00:00+00:00,35,1,102338,1195.0,1213.0,1195.0,1210.2,18,GC.c.0
2010-07-12 00:00:00+00:00,35,1,102338,1205.7,1206.2,1204.0,1204.8,45,GC.c.0
2010-07-13 00:00:00+00:00,35,1,102338,1205.2,1217.4,1205.2,1213.0,53,GC.c.0
2010-07-14 00:00:00+00:00,35,1,102338,1212.0,1216.0,1202.4,1209.2,54,GC.c.0
2010-07-15 00:00:00+00:00,35,1,102338,1213.2,1213.2,1208.4,1209.6,32,GC.c.0

In [17]:
conditions = client.metadata.get_dataset_condition(
    dataset="GLBX.MDP3",
    start_date="2010-06-06",
    end_date="2025-08-18",
)

In [21]:
conditions_df = pd.DataFrame(conditions)
conditions_df['condition'].value_counts()

available    4749
degraded       11
Name: condition, dtype: int64

In [41]:
df.to_csv("gold_continuous_futures.csv")